apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: team2-flux
  namespace: gitops
spec:
  chart:
    git: https://github.com/nniikkoollaaii/GitOps_K8s_Cluster_via_Terraform
    path: "helm/flux"
    secretRef: 
      name: "git-auth"
  releaseName: team2-flux
  version: 1.0.0
  targetNamespace: "team2-mgmt"
  values:
    image:
      repository: "fluxcd/flux"
    git:
      url: "https://$(username):$(password)@github.com/nniikkoollaaii/GitOps_K8s_Cluster_via_Terraform_Config_Team2_Manifests.git"
      branch: "master"
      user: "nniikkoollaaii"
      email: "<email>"
      path: "manifests"
      pollInterval: "1m"
    env:
      secretName: "git-auth"
    clusterRole:
      create: false
    registry:
      disableScanning: true
    syncGarbageCollection:
      enabled: true
    allowedNamespaces: ["team2-dev", "team2-prod"] # team2-mgmt automaticly