apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: team1-flux
  namespace: gitops
spec:
  chart:
    git: https://github.com/nniikkoollaaii/GitOps_K8s_Cluster_via_Terraform
    path: "terraform/helm-operator"
    secretRef: 
      name: "flux-git-auth"
    releaseName: app1
    version: 1.0.0
    targetNamespace: "team1"
    values:
      - image.repository: "fluxcd/flux"
      - git.url: "https://$(GIT_AUTHUSER):$(GIT_AUTHKEY)@github.com/nniikkoollaaii/GitOps_K8s_Cluster_via_Terraform_Config.git"
      - git.branch: "master"
      - git.user: "nniikkoollaaii"
      - git.email: "<email>"
      - git.path: "manifests"
      - env.secretName: "flux-git-auth"
      - registry.disableScanning: "true"
      - allowedNamespaces: ["team1"]