apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: team1-flux
  namespace: gitops
spec:
  chart:
    git: https://github.com/nniikkoollaaii/GitOps_K8s_Cluster_via_Terraform
    path: "helm/flux"
    secretRef: 
      name: "git-auth"
    releaseName: team1-flux
    version: 1.0.0
  targetNamespace: "team1"
  values:
    image:
      repository: "fluxcd/flux"
    git:
      url: "https://$(username):$(password)@github.com/nniikkoollaaii/GitOps_K8s_Cluster_via_Terraform_Config_Team1.git"
      branch: "master"
      user: "nniikkoollaaii"
      email: "<email>"
      path: "manifests"
      pollInterval: "1m"
    env:
      secretName: "git-auth"
    clusterRole:
      create: false
    registry:
      disableScanning: true
    syncGarbageCollection:
      enabled: true