apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: team1-helm-operator
  namespace: gitops
spec:
  chart:
    git: https://github.com/nniikkoollaaii/GitOps_K8s_Cluster_via_Terraform
    #ref: master
    path: "helm/helm-operator"
    secretRef: 
      name: "git-auth"
  releaseName: team1-helm-operator
  version: 1.0.0
  wait: true
  targetNamespace: "team1"
  values:
    image:
      repository: "fluxcd/helm-operator"
      tag: "1.0.0"
    createCRD: false
    clusterRole:
      create: false
    allowNamespace: "team1"
    git:
      pollInterval: "1m"  
    helm:
      versions: "v3"