apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: team1-helm-operator
  namespace: gitops
spec:
  chart:
    git: https://github.com/nniikkoollaaii/GitOps_K8s_Cluster_via_Terraform
    path: "helm/helm-operator"
    secretRef: 
      name: "git-auth"
    releaseName: team1-helm-operator
    version: 1.0.0
    targetNamespace: "team1"
    values:
      image.repository: "fluxcd/helm-operator"
      image.tag: "1.0.0"
      createCRD: "false"
      allowNamespace: "team1"
      git.pollInterval: "1m"  
      helm.versions: "v3"